// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yqudyhorxqkneukoegwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxdWR5aG9yeHFrbmV1a29lZ3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NTI5NTQsImV4cCI6MjA4ODMyODk1NH0.bFqd9qcIsR5Q2UVkPe_B1lVh78AoX76sVBf1m2VZb1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);